.TH "LOAD TPM KEY" 8 "Oct 2010" "" ""
.SH NAME
tpm_loadkey
.SH SYNOPSIS
.B tpm_loadkey
.RB [ \-r\ HOST ]
.RB [ \-hv ]
.RI BLOB-FILE
.RI UUID-FILE
.br
.SH DESCRIPTION
.PP
The program loads the key in
.RI BLOB-FILE
into persistent storage and registers it using the UUID in
.RI UUID-FILE.
.TP
.RB \-r\ HOST
Perform operation on remote
.RB HOST.
.TP
.RB \-h
Display command usage info.
.TP
.RB \-v
Display command version info.
.SH "SEE ALSO"
.BR tpm_quote_tools "(8),"
.BR tpm_mkuuid "(8),"
.BR tpm_mkaik "(8),"
.BR tpm_unloadkey "(8)"
