.TH "MAKE TPM UUID" 8 "Oct 2010" "" ""
.SH NAME
tpm_mkuuid
.SH SYNOPSIS
.B tpm_uuid
.RB [ \-hv ]
.RI UUID-FILE
.br
.SH DESCRIPTION
.PP
The program generates a TPM UUID and stores it in the file
.RI UUID-FILE.
.TP
.RB \-h
Display command usage info.
.TP
.RB \-v
Display command version info.
.SH "SEE ALSO"
.BR tpm_quote_tools "(8)"
